# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timeserieswidget_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(469, 127)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.start_time = QtWidgets.QPushButton(Form)
        self.start_time.setAutoRepeat(False)
        self.start_time.setObjectName("start_time")
        self.horizontalLayout_2.addWidget(self.start_time)
        self.datetime_edit = QtWidgets.QDateTimeEdit(Form)
        self.datetime_edit.setTimeSpec(QtCore.Qt.UTC)
        self.datetime_edit.setObjectName("datetime_edit")
        self.horizontalLayout_2.addWidget(self.datetime_edit)
        self.end_time = QtWidgets.QPushButton(Form)
        self.end_time.setObjectName("end_time")
        self.horizontalLayout_2.addWidget(self.end_time)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fastbackward_time = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fastbackward_time.sizePolicy().hasHeightForWidth())
        self.fastbackward_time.setSizePolicy(sizePolicy)
        self.fastbackward_time.setAutoRepeat(True)
        self.fastbackward_time.setAutoRepeatInterval(50)
        self.fastbackward_time.setObjectName("fastbackward_time")
        self.horizontalLayout.addWidget(self.fastbackward_time)
        self.backward_time = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backward_time.sizePolicy().hasHeightForWidth())
        self.backward_time.setSizePolicy(sizePolicy)
        self.backward_time.setAutoRepeat(True)
        self.backward_time.setAutoRepeatInterval(50)
        self.backward_time.setObjectName("backward_time")
        self.horizontalLayout.addWidget(self.backward_time)
        self.play = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play.sizePolicy().hasHeightForWidth())
        self.play.setSizePolicy(sizePolicy)
        self.play.setCheckable(True)
        self.play.setObjectName("play")
        self.horizontalLayout.addWidget(self.play)
        self.forward_time = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forward_time.sizePolicy().hasHeightForWidth())
        self.forward_time.setSizePolicy(sizePolicy)
        self.forward_time.setAutoRepeat(True)
        self.forward_time.setAutoRepeatInterval(50)
        self.forward_time.setObjectName("forward_time")
        self.horizontalLayout.addWidget(self.forward_time)
        self.fastforward_time = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fastforward_time.sizePolicy().hasHeightForWidth())
        self.fastforward_time.setSizePolicy(sizePolicy)
        self.fastforward_time.setAutoRepeat(True)
        self.fastforward_time.setAutoRepeatInterval(50)
        self.fastforward_time.setObjectName("fastforward_time")
        self.horizontalLayout.addWidget(self.fastforward_time)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalSlider = QtWidgets.QSlider(Form)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout.addWidget(self.horizontalSlider)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.start_time.setText(_translate("Form", "|<"))
        self.datetime_edit.setDisplayFormat(_translate("Form", "dd/MM/yyyy HH:mm"))
        self.end_time.setText(_translate("Form", ">|"))
        self.fastbackward_time.setText(_translate("Form", "<<"))
        self.backward_time.setText(_translate("Form", "<"))
        self.play.setText(_translate("Form", "Play"))
        self.forward_time.setText(_translate("Form", ">"))
        self.fastforward_time.setText(_translate("Form", ">>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
